create type public.app_role as enum ('admin', 'tenant');
--> statement-breakpoint
create type public.app_permission as enum (
  'dashboard.view',
  'rooms.manage',
  'tenants.manage',
  'assignments.manage',
  'bills.manage',
  'payments.manage',
  'billing.view_all',
  'billing.view_own'
);
--> statement-breakpoint
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role public.app_role not null,
  unique (user_id)
);
--> statement-breakpoint
create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);
--> statement-breakpoint
alter table public.user_roles enable row level security;
--> statement-breakpoint
alter table public.role_permissions enable row level security;
--> statement-breakpoint
revoke all on table public.user_roles from authenticated, anon, public;
--> statement-breakpoint
revoke all on table public.role_permissions from authenticated, anon, public;
--> statement-breakpoint
insert into public.role_permissions (role, permission) values
  ('admin', 'dashboard.view'),
  ('admin', 'rooms.manage'),
  ('admin', 'tenants.manage'),
  ('admin', 'assignments.manage'),
  ('admin', 'bills.manage'),
  ('admin', 'payments.manage'),
  ('admin', 'billing.view_all'),
  ('tenant', 'billing.view_own');
--> statement-breakpoint
insert into public.user_roles (user_id, role)
select id, role::public.app_role from public.profiles
on conflict (user_id) do nothing;
--> statement-breakpoint
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'tenant')
  on conflict (user_id) do nothing;

  return new;
end;
$$;
--> statement-breakpoint
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role from public.user_roles
  where user_id = (event->>'user_id')::uuid;

  claims := event->'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;

  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;
--> statement-breakpoint
grant usage on schema public to supabase_auth_admin;
--> statement-breakpoint
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
--> statement-breakpoint
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;
--> statement-breakpoint
grant all on table public.user_roles to supabase_auth_admin;
--> statement-breakpoint
create policy "Allow auth admin to read user roles" on public.user_roles
  as permissive for select to supabase_auth_admin using (true);
--> statement-breakpoint
create or replace function public.has_permission(
  requested_permission public.app_permission
)
returns boolean as $$
declare
  bind_permissions int;
  user_role public.app_role;
begin
  select (auth.jwt() ->> 'user_role')::public.app_role into user_role;

  select count(*) into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$$ language plpgsql stable security definer set search_path = '';